### ISSUE TITLE
Support blocking search engines (support custom <head> content?)

### ISSUE THREAD

**Issue by tsmacdonald** [clj-commons/marginalia#186]
My motivating case is wanting to add a `<meta name="robots contents="noindex">` to the `<head>` to block search engines from indexing the docs, but as I think about it it'd probably be best to support poking arbitrary content in there (maybe for opengraph attributes?).

**Comment by seancorfield** [comment]
Can you explain why you wouldn't want search engines to index publicly available uberdocs?

Also, is this a case of wanting a control to enable this or a control to insert `<head>` content or...?

**Comment by seancorfield** [comment]
It seems reasonable to add a `:meta` option to the `:marginalia` key in `project.clj` that could be a hash map of name/contents:
```clojure
  :marginalia {:meta {:robots "noindex"}}
```
That would produce:
```html
<meta name="robots" content="noindex">
```
in the `<head>` tag -- but could be used to insert other `<meta>` tags.

**Comment by seancorfield** [comment]
Marginalia 0.9.2 released with this (and many other) fixes.
