### ISSUE TITLE
chokes on my project.clj

### ISSUE THREAD

**Issue by cvillecsteele** [clj-commons/marginalia#24]
My project.clj looks a bit like:

```
;; Pick up special frobbing
(require 'mine.frob)

(defproject flib
  (frob/twiggle)
  "Flib at high speed"
  ...)
```

And I would love to use marginalia but it chokes on my project.clj!  :( Sadness.

**Comment by TreeRex** [comment]
This happens on my project.clj as well, which starts like:

    (def wombat-version "1.1.0-SNAPSHOT")
    ;; BUILD_NUMBER is set by Jenkins
    (def build-number (or (System/getenv "BUILD_NUMBER")
                          (str "dev-" (.format (java.text.SimpleDateFormat. "yyyyMMddHHmmss")
                                               (java.util.Date.)))))
    (def release-version (str wombat-version \. build-number))
    
    (defproject wombat release-version
      :description "Wombat's are wicked"
      ;;...
      )

I can obviously inline all of the above into `defproject` but I'd rather not.

**Comment by tsmacdonald** [comment]
Turns out this was fixed in [this commit](https://github.com/clj-commons/marginalia/commit/1dbbd42862b270a10f6ed9ce071ea247dde3baf8) ten years ago (!) but the issue was never closed.
